services:
  mysql:
    image: mysql:8.0
    container_name: flask_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: flask_app
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask_network

  redis:
    image: redis:7-alpine
    container_name: flask_redis
    restart: unless-stopped
    command: >
      redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    networks:
      - flask_network

  flask:
    image: ghcr.io/artemkill0/bls-backend:latest
    container_name: flask_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DB: flask_app
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    depends_on:
      - mysql
      - redis
    networks:
      - flask_network

volumes:
  mysql_data:
  redis_data:

networks:
  flask_network: