name: Deploy BLS Backend
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf /bls/*
          cd /bls
          git clone "https://artemkill0:$DEPLOY_TOKEN@github.com/artemkill0/BLS-Mood-Friends-backend.git" .
          ls -la
          cd /bls
          test -f docker-compose.yml && docker compose up -d --build || echo "NO docker-compose.yml"
